### ISSUE TITLE
the mean of g__; s__

### ISSUE THREAD

**Issue by wz115** [wasade/q2-greengenes2#27]
some sequences with taxonomy like this:
MJ006-1-barcode39-umi160260bins-ubs-3   d__Bacteria; p__Firmicutes_A; c__Clostridia_258483; o__Lachnospirales; f__Lachnospiraceae; g__; s__

does it means this a new species(unnamed species)  or ambiguous( like Shigella  and E.coli)?

**Comment by wasade** [comment]
Within the phylogeny, it means either an existing name didn't have sufficient evidence for decoration during tax2tree, or no names have been associated to records in that clade
