### ISSUE TITLE
What file(s) on the GG2db ftp site can be used as reference-taxonomy for classification by q2-greengenes2 plugin?

### ISSUE THREAD

**Issue by VoronDM** [wasade/q2-greengenes2#28]
Hi,

I tried to classify my amplicons sequences with q2-greengenes2 plugin. Unsuccessfully.

What file(s) on the ftp can be used for classification using q2-greengenes2 plugin as **--i-reference-taxonomy**?
Do I understand correctly that a file with multiple amplicons sequences (.qza) can be used as input in **--i-reads**?

$ qiime greengenes2 taxonomy-from-features \
    **--i-reference-taxonomy <the_greengenes_reference>** \
    **--i-reads <your_FeatureData[Sequence]>** \ 
    --o-classification <the_resulting_classifications>

Thanks.

**Comment by wasade** [comment]
Hi @VoronDM, as this relates to QIIME 2, could you please first check the QIIME 2 Forum, and open a thread on there if needed? 

The reference taxonomy to use would depend on how your ASVs are expressed and upstream processing. But, if I remember correctly of that input, you could use `2024.09.taxonomy.asv.nwk.qza`. The reads would need to be, as noted, a `FeatureData[Sequence]` artifact.
